file_format: "1"
id: quefrency65macro
name: Quefrency Rev. 1 65% Macro
type: shield
url: https://github.com/keebio/quefrency-rev1-pcb
requires: [nice_nano_v2]
features:
  - keys
siblings:
  - quefrency65macro_left
  - quefrency65macro_right
